### ISSUE TITLE
import is buggy

### ISSUE THREAD

**Issue by behconsci** [pytonik/pytonik_ip_vpn_checker#1]
from pytonik_ip_vpn_checker.ip import ip

says pycharm, it can't be imported: 

    from pytonik_ip_vpn_checker.ip import ip
ModuleNotFoundError: No module named 'pytonik_ip_vpn_checker'

![image](https://user-images.githubusercontent.com/10358323/74580011-e6df2700-4f9f-11ea-8edd-2ba6e3775222.png)

**Comment by pytonik** [comment]
reinstall it using pip install pytonik_ip_vpn_checker==1.0.6 and import it again

**Comment by behconsci** [comment]
ok thanks
